### ISSUE TITLE
Unpacking dependencies duplicates files when two different versions of a dependency exist in the dependency tree

### ISSUE THREAD

**Issue by joh-ivu** [ascopes/protobuf-maven-plugin#134]
In a company-internal project I have the following setup:
* The FooBar project shall publish some .proto files
* Those protos depend on other protos coming from Maven dependencies. There are three dependencies in total:
  * com.google.api.grpc:proto-google-common-protos (a jar with both .class and .proto files)
  * my.company:stuff (a zip with .proto files)
  * my.company:things (a zip with .proto files)
* my.company:things in turn depends on stuff and proto-google-common-protos. On of course, all of them depend on the well known types like StringValue. This way, proto-google-common-protos and protobuf-java are present twice in the dependency tree, but as is so often the case in two different versions.

The unpacking of dependencies does not seem to take this into account leading to duplicate files:

![2024-03-20 10_39_15-Window](https://github.com/ascopes/protobuf-maven-plugin/assets/153828417/4e77daf6-d904-40ee-93e3-8a8225e4dd24)

**Comment by ascopes** [comment]
At the moment, the code doesn't deal with differentiating between multiple versions of the same dependency, which appears to be the issue here. I could probably deduplicate based upon the group ID and artifact ID though to avoid this. I'd need to take a look at how the dependency resolver API exposes this detail. When I get time I will do that though (I'm not going to have much time for the next couple of weeks so it might have to wait until then).

A workaround for now would be to explicitly exclude the dependencies you don't want in the dependencies block.

Also can see GH-135 related to this that would provide another solution.

**Comment by ascopes** [comment]
@joh-ivu I've just made an unrelated change that updates how dependency resolution works. One of the things I changed was that any Maven-based project dependencies will now make use of the original Maven project dependency resolution rather than re-resolving all dependencies twice.

It would appear that a side effect of doing this is that it may now be deduplicating these dependencies in the way that you would expect. The test case for GH-132 which resulted in duplicate dependencies being output now appears to only be taking in one copy of protobuf-java despite depending on 4 modules that all depend on it transitively.

Would you mind retesting using the latest build on `main` and see if it now follows your expectations? If it does not, I may need to get some more details from you about reproducing this issue. If it does fix it, then this will be fixed in v1.2.0 which will be released once I've addressed your other issue at GH-135.

Sorry it has taken so long!

**Comment by ascopes** [comment]
I have looked into this further and I believe that this is fixed by the changes I've added to main. If you see any further issues aside from this, please can you reraise a new issue or ping me here and I shall reopen this issue!
