### ISSUE TITLE
"Error: Invalid or corrupt jarfile" when developing java protoc plugins

### ISSUE THREAD

**Issue by rmichela** [ascopes/protobuf-maven-plugin#358]
While writing a custom Java protoc generator, I'd like to be able to use the protobuf-maven-plugin to compile my proto files and test the generator. However, I'm running into an issue where the plugin is not able to find my custom generator class when using `mvn compile`.

I've created a repro repo that demonstrates the problem https://github.com/rmichela/protobuf-maven-plugin-bug.

**Comment by ascopes** [comment]
Hey, thanks for raising an issue.

I'm not able to get to a computer at the moment as I am on holiday, would you be able to provide the full error message you are seeing?

This plugin handles Java plugins by just writing a shell script that invokes the JAR directly, you'll see that in `target/protobuf-maven-plugin`, and that injects the classpath, etc. You should be able to invoke that directly to test the script that is produced.

My first guess is that you may need to `mvn install` the JAR for the generator first? Have you given that a try as well? Thanks!

**Comment by ascopes** [comment]
Ah, I see the README in your repo has this exact detail I need. Okay. So I think if you run `mvn install` first on the first package, it will avoid the issue as a workaround. However, I can see it is because it is passing the classes directory to the java executable under the JAR argument. This should be a simple fix once I get to a computer to sort it out. I think we just need to check for whether the plugin is a file or a directory [here](https://github.com/ascopes/protobuf-maven-plugin/blob/main/protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java#L138) and apply the flags accordingly.

**Comment by ascopes** [comment]
@rmichela please can you clone from the main branch, build this project, and verify that it fixes the issues you were seeing on your side? It should be working now (per my reproduction I put together) but I'd like to be sure it addresses your issues fully before I release anything.

Thanks!

**Comment by rmichela** [comment]
Verified fixed. Thank you!

**Comment by ascopes** [comment]
Cool, should be available on 2.5.0 for use!
